spring:
  application:
    name: CapitalInvest

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 2579443818883294
            clientSecret: f84ad192ddd85b84792d5e1f6afa1e81
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
          resource:
            userInfoUri: https://graph.facebook.com/me

